/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Util.TxtFilter;
import Business.ID3.RecordBuilder;
import Business.ID3.Node;
import Business.ID3.Record;
import Business.ID3.DecisionTree;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sonam
 */
public class TrainMachineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrainMachineJPanel
     */
    private JPanel userProcessContainer;
    private Node root;
    public TrainMachineJPanel(JPanel userProcessContainer,Node root) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.root=root;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filePathJTextField = new javax.swing.JTextField();
        browseJButton = new javax.swing.JButton();
        createDecisionTreeJButton = new javax.swing.JButton();

        browseJButton.setText("Browse");
        browseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseJButtonActionPerformed(evt);
            }
        });

        createDecisionTreeJButton.setText("Create Decisino Tree");
        createDecisionTreeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDecisionTreeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filePathJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(browseJButton))
                    .addComponent(createDecisionTreeJButton))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filePathJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createDecisionTreeJButton)
                .addContainerGap(426, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseJButtonActionPerformed
        // TODO add your handling code here:
        String userDir = System.getProperty("user.home");
        JFileChooser chooser = new JFileChooser(userDir +"/Desktop");
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(new TxtFilter());
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setMultiSelectionEnabled(false);

        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String fileName=file.getAbsolutePath();
            filePathJTextField.setText(fileName);
        }
    }//GEN-LAST:event_browseJButtonActionPerformed

    private void createDecisionTreeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDecisionTreeJButtonActionPerformed
        // TODO add your handling code here:
        String filePath= filePathJTextField.getText();
        if(filePath.length()==0)
        {
            JOptionPane.showMessageDialog(this,"Please enter correct file name","Error!!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try
        {
            File f = new File(filePath);
            if(!f.exists() || f.isDirectory()) 
            {
                JOptionPane.showMessageDialog(this,"File not exists","Error!!!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,"File not exists","Error!!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        DecisionTree t = new DecisionTree();
        ArrayList<Record> records;
        records = RecordBuilder.buildRecords(filePath);
        
        for (Record record : records) {
            root.getData().add(record);
        }

        root=t.buildTree(records, root);
        for (Record record : records) {
            DecisionTree.getDecision(record, root);
           // System.out.println("*********************************************************");
        }
        System.out.println(root);
        JOptionPane.showMessageDialog(this,"Decision Tree Created","Information!!!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_createDecisionTreeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseJButton;
    private javax.swing.JButton createDecisionTreeJButton;
    private javax.swing.JTextField filePathJTextField;
    // End of variables declaration//GEN-END:variables
}
